services:
  - type: web
    name: ngo-volunteer-app
    env: java
    plan: free
    region: ohio
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ngoApp-0.0.1-SNAPSHOT.jar
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: ngo-volunteer-data
      mountPath: /opt/render/project/data
      sizeGB: 1
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: APP_BASE_URL
        value: https://ngo-volunteer-app.onrender.com
